version: "3.8"

services:
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1234
    # bind mount volume for MongoDB documents
    volumes:
      - './mongo-data:/data/db'   
      - './mongo-app:/var/www/html'
    ports:
      - "27017:27017"
    # configure the Docker entrypoint for MongoDB

